export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const GET_POSTS = 'GET_POSTS';
export const GOT_POSTS_SUCCESS = 'GOT_POSTS_SUCCESS';
export const GOT_POSTS_ERROR = 'GOT_POSTS_ERROR';

export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const GOT_POST_DETAILS_SUCCESS = 'GOT_POST_DETAILS_SUCCESS';
export const GOT_POST_DETAILS__ERROR = 'GOT_POST_DETAILS__ERROR';

export const REMOVE_POST = 'REMOVE_POST';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_ERROR = 'REMOVE_POST_ERROR';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';

export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

export const GET_AUTHORS = 'GET_AUTHORS';
export const GOT_AUTHORS_SUCCESS = 'GOT_AUTHORS_SUCCESS';
export const GOT_AUTHORS_ERROR = 'GOT_AUTHORS_ERROR';

export const GET_TAGS = 'GET_POSTS';
export const GOT_TAGS_SUCCESS = 'GOT_TAGS_SUCCESS';
export const GOT_TAGS_ERROR = 'GOT_TAGS_ERROR';